# Generated by Django 5.2.7 on 2025-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='service_mode',
            field=models.CharField(choices=[('book', 'Book'), ('cic_service', 'CIC Service'), ('ngo_service', 'NGO Service'), ('course', 'Course')], default='service', max_length=50),
        ),
    ]
