# Generated by Django 5.2.7 on 2025-10-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_book_contactmessage_course_bookorder_courselesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='free_chapter_pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
