# Generated by Django 5.2.7 on 2025-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_book_cover_image_alter_book_free_chapter_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='what_readers_will_learn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
