# Generated by Django 5.2.7 on 2025-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_book_what_readers_will_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor_name',
            field=models.URLField(default='Zion Oshiobugie', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
