# Generated by Django 5.2.7 on 2025-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_course_instructor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
