# Generated by Django 5.2.7 on 2025-10-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_course_instructor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='resource',
            field=models.URLField(blank=True, null=True),
        ),
    ]
