# Generated by Django 5.2.7 on 2025-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_courselesson_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='Zion Oshiobugie', max_length=100),
        ),
    ]
