# Generated by Django 5.2.7 on 2025-10-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_course_instructor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookOrder',
        ),
    ]
