# Generated by Django 5.2.7 on 2025-10-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_delete_bookorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('ngo', 'NGO Strategy Call'), ('cic', 'CIC Strategy Call')], max_length=10)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('stage', models.CharField(choices=[('idea', 'Still an idea'), ('registering', 'Currently registering'), ('registered', 'Already registered'), ('growing', 'Active and growing')], max_length=50)),
                ('goal', models.TextField(help_text='What’s your main goal for this session?')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
