# Generated by Django 5.2.7 on 2025-10-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_strategycall'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=200)),
                ('event_structure', models.CharField(choices=[('keynote', 'Keynote Speech'), ('panel', 'Panel Discussion'), ('podcast', 'Podcast'), ('masterclass', 'Masterclass'), ('workshop', 'Workshop / Training'), ('other', 'Other')], help_text='Select the type of event you’re inviting Zion for.', max_length=50)),
                ('message', models.TextField(help_text='Brief description of your event and audience.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Speaker Invitation',
                'verbose_name_plural': 'Speaker Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
