# Generated by Django 5.2.7 on 2025-10-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_payment_delete_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
