# Generated by Django 5.2.7 on 2025-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_payment_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
