# Generated by Django 5.2.7 on 2025-10-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_payment_satisfied'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Book Payment',
                'verbose_name_plural': 'Book Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('services.payment',),
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
            ],
            options={
                'verbose_name': 'Course Payment',
                'verbose_name_plural': 'Course Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('services.payment',),
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
            ],
            options={
                'verbose_name': 'Service Payment',
                'verbose_name_plural': 'Service Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('services.payment',),
        ),
        migrations.AlterField(
            model_name='book',
            name='what_readers_will_learn',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
