# Generated by Django 5.2.7 on 2025-10-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_bookpayment_coursepayment_servicepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='what_you_learn',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='who_is_for',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
