# Generated by Django 5.2.7 on 2025-10-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_course_what_you_learn_alter_course_who_is_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ideal_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
