# Generated by Django 5.2.7 on 2025-10-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_book_ideal_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(default='', editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
